### ISSUE TITLE
[grails4] NoClassDefFoundError on startup

### ISSUE THREAD

**Issue by longwa** [agileorbit/grails-schwartz#14]
Grails 4.0.0.M1

Looks like the `QuartzService` is using the defunct `grails.transaction.Transactional` which has been removed in Grails 4.

This causes a `NoClassDefFoundError` on startup in Grails 4.
```
java.lang.NoClassDefFoundError: grails/transaction/GrailsTransactionTemplate
        at com.agileorbit.schwartz.QuartzService.init(QuartzService.groovy)
        at com.agileorbit.schwartz.QuartzService$init.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at com.agileorbit.schwartz.SchwartzGrailsPlugin.doWithApplicationContext(SchwartzGrailsPlugin.groovy:77)
```
I think it should be using `grails.gorm.transactions.Transactional` instead.

**Comment by robertoschwald** [comment]
There is much more to migrate for Grails 4.0.0. Hibernate Mappings, etc. has gone in Hibernate 5.

**Comment by longwa** [comment]
We will start working on migrating our project to 4 soon. I planned on spending some time on the audit plugin as well. 

-Aaron

**Comment by robertoschwald** [comment]
@erichelgeson started to port to Grails4 already. Havn‘t checked the status of it, yet.

**Comment by longwa** [comment]
He and I collaborated a bit a couple months ago on M1. He has a good list of migration issues. I had a few show stoppers that I ended up not having time to chase down. I do believe I have a working copy of the audit logging plugin though. I’ll push a working branch if I do. 

-Aaron

**Comment by erichelgeson** [comment]
I have a Grails 4 branch https://github.com/agileorbit/grails-schwartz/tree/eric/grails4 with it mostly working - 1 test failing right now. I chose to remove the automated changelog generation as it used many liquibase/hibernate methods that are now gone. Also while a nice feature, not critical for a M1 release. 

I'll ping @bobbywarner and see if we can push a M1 from my branch so people can get testing and temp ignore the 1 test failure (which may just be a race condition in the test)

**Comment by erichelgeson** [comment]
FYI there's a `2.0.0.RC1` published now. Please let me know!
