### ISSUE TITLE
Grails 4 + schwartz 2.0.0 RC1: java.lang.NoSuchFieldError: PROP_SCHED_SKIP_UPDATE_CHECK

### ISSUE THREAD

**Issue by mhemani** [agileorbit/grails-schwartz#15]
Grails 4 + schwartz 2.0.0 RC1

- Created a new basic HelloWorldJobService
- Error on run-app:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'quartzScheduler': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.agileorbit.schwartz.SchwartzSchedulerFactoryBean]: Constructor threw exception; nested exception is java.lang.NoSuchFieldError: PROP_SCHED_SKIP_UPDATE_CHECK
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:304)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:285)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1187)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:826)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:97)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:458)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:445)
	at myapp.Application.main(Application.groovy:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.agileorbit.schwartz.SchwartzSchedulerFactoryBean]: Constructor threw exception; nested exception is java.lang.NoSuchFieldError: PROP_SCHED_SKIP_UPDATE_CHECK
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:184)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:300)
	... 25 common frames omitted
Caused by: java.lang.NoSuchFieldError: PROP_SCHED_SKIP_UPDATE_CHECK
	at com.agileorbit.schwartz.SchwartzSchedulerFactoryBean.buildQuartzProperties(SchwartzSchedulerFactoryBean.groovy:137)
	at com.agileorbit.schwartz.SchwartzSchedulerFactoryBean.<init>(SchwartzSchedulerFactoryBean.groovy:69)
	at sun.reflect.GeneratedConstructorAccessor49.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
	... 27 common frames omitted
```

**Comment by erichelgeson** [comment]
Can you share a sample app? What version of quartz are you defining in build.gradle?

**Comment by mhemani** [comment]
Sample app is the basic guide from:
https://guides.grails.org/grails-schwartz/guide/index.html

No quartz version defined in the build.gradle.

**Comment by erichelgeson** [comment]
That guide is for Grails 3.3.2.

Due to the way gradle 5 resolves transitive dependencies differently then before you must define the quartz version. Please see the integration test app in this repo on the grails 4 branch.

**Comment by mhemani** [comment]
From that repo, what I gather is that the quartz dependency needed is:

	String quartzVersion = '2.2.3'
	compile 'org.quartz-scheduler:quartz:' + quartzVersion, {
		exclude module: 'c3p0'
	}
	compile 'org.quartz-scheduler:quartz-jobs:' + quartzVersion

Would this also hold true for 2.3.1?

**Comment by erichelgeson** [comment]
I have not tested with 2.3.1, likely be a quick 2.0 release and then a 2.3.x compatible release after.

**Comment by mhemani** [comment]
I can confirm that it works with 2.2.3 but not with 2.3.1.

Thank you for the assist!

**Comment by erichelgeson** [comment]
FYI the docs will be updated to include this, just time right now - appreciate the report. Let us know if you run into anything else.
