### ISSUE TITLE
Using grails mail plugin causes exception due to LinkGenerator.serverBaseURL == null

### ISSUE THREAD

**Issue by erichelgeson** [agileorbit/grails-schwartz#3]
``` groovy
mailService.sendMail {
        to cluster.email
        from grailsApplication.config.getProperty('example.mail.from')
        subject "Cluster ready"
        body(view: "/email/_clusterReady", model: [clusterUrl: cluster?.url])
        async true
}
```

Using `body` the `LinkGenerator.serverBaseURL` is null, causing this exception:

```
ERROR org.quartz.core.JobRunShell - Job DEFAULT.ClusterJobService threw an unhandled Exception: 
java.lang.NullPointerException: null
    at java.net.URI$Parser.parse(URI.java:3042)
    at java.net.URI.<init>(URI.java:588)
    at grails.plugins.mail.MailMessageContentRenderer$PageRenderRequestCreator.createInstance(MailMessageContentRenderer.groovy:192)
    at grails.plugins.mail.MailMessageContentRenderer$RenderEnvironment.init(MailMessageContentRenderer.groovy:141)
    at grails.plugins.mail.MailMessageContentRenderer$RenderEnvironment.with(MailMessageContentRenderer.groovy:172)
    at grails.plugins.mail.MailMessageContentRenderer.render(MailMessageContentRenderer.groovy:57)
    at grails.plugins.mail.MailMessageContentRenderer$render.call(Unknown Source)
    at grails.plugins.mail.MailMessageBuilder.doRender(MailMessageBuilder.groovy:276)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1432)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
    at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
    at grails.plugins.mail.MailMessageBuilder.body(MailMessageBuilder.groovy:258)
    at com.example.ClusterJobService$_execute_closure2.doCall(ClusterJobService.groovy:82)
```

Though the same code works in a controller in the same app.

**Comment by AlexKovynev** [comment]
it's not plugin error. quartz plugin give the same. 
Simple add grails.serverURL = "http://localhost:8080" to application.groovy or .yml in development section.
